In [1]:
import numpy as np
import pandas as pd


In [25]:
df = pd.read_csv('data.csv')

In [26]:
df.head()

A   B     C     D
0  10  20  30.0  40.0
1   1   2   NaN   NaN
2   5   6   NaN   8.0
3   0  11  12.0   NaN

In [27]:
df.tail()

A   B     C     D
0  10  20  30.0  40.0
1   1   2   NaN   NaN
2   5   6   NaN   8.0
3   0  11  12.0   NaN

In [28]:
df.isnull().sum()

A    0
B    0
C    2
D    2
dtype: int64

In [29]:
df.describe()

A          B          C          D
count   4.000000   4.000000   2.000000   2.000000
mean    4.000000   9.750000  21.000000  24.000000
std     4.546061   7.762087  12.727922  22.627417
min     0.000000   2.000000  12.000000   8.000000
25%     0.750000   5.000000  16.500000  16.000000
50%     3.000000   8.500000  21.000000  24.000000
75%     6.250000  13.250000  25.500000  32.000000
max    10.000000  20.000000  30.000000  40.000000

In [30]:
df.dropna(axis=1)

A   B
0  10  20
1   1   2
2   5   6
3   0  11

In [31]:
df.dropna(subset=['C'])

A   B     C     D
0  10  20  30.0  40.0
3   0  11  12.0   NaN

In [32]:
df.dropna(thresh=3)

A   B     C     D
0  10  20  30.0  40.0
2   5   6   NaN   8.0
3   0  11  12.0   NaN

In [38]:
from sklearn.impute import SimpleImputer


In [39]:
si = SimpleImputer(strategy='mean')

In [40]:
df1 = si.fit_transform(df)

In [41]:
df1

array([[10., 20., 30., 40.],
       [ 1.,  2., 21., 24.],
       [ 5.,  6., 21.,  8.],
       [ 0., 11., 12., 24.]])

In [42]:
si = SimpleImputer(strategy='median')

In [43]:
df2 = si.fit_transform(df)

In [44]:
df2

array([[10., 20., 30., 40.],
       [ 1.,  2., 21., 24.],
       [ 5.,  6., 21.,  8.],
       [ 0., 11., 12., 24.]])

In [45]:
si = SimpleImputer(strategy='most_frequent')

In [46]:
df4 = si.fit_transform(df)

In [47]:
df4

array([[10., 20., 30., 40.],
       [ 1.,  2., 12.,  8.],
       [ 5.,  6., 12.,  8.],
       [ 0., 11., 12.,  8.]])