# CHECK GIVEN ELEMENT IS SCALAR OR NOT 

In [1]:
import numpy as np

In [13]:
a =np.array([[1,2,3],[4,5,-1],[7,4,-2]])
a


# print(np.square(a[1][]))
# print(np.linalg.det(a))
print(a.reshape(1,9))

[[ 1  2  3  4  5 -1  7  4 -2]]


In [33]:
# a = np.array([[1,2],[3,4]])
# b = np.array([8,18])
# print((np.linalg.solve(a,b)))

a = [[9,4]]
b = [[5,6],[9,8]]
np.outer(a,b)
# numbers = (4,7,19,2,89,45,72,22)
# sorted_numbers = sorted(numbers)
# print(type(sorted_numbers))

# dict1 = {'first':'sunday','second':'monday'}
# dict2 = {1:3,2:4}
# dict1.update(dict2)
# print(dict1)

# a= {'Hello':'World', 'First':1}
# b = {val:k for k, val in a.items()}
# print(b)

# example = ["Sunday","Monday","Tuesday","Wednesday"];
# print(example[-3:-1])

array([[45, 54, 81, 72],
       [20, 24, 36, 32]])

In [2]:
a = [1,2,3,4,4,5]
b = 5

In [3]:
isScaler_value1 = np.isscalar(a)
# isScaler_value1 = numpy.isscalar(a) // not working while use numpy after defining as np
isScaler_value2 = np.isscalar(b)

In [4]:
print(isScaler_value1)

False


In [5]:
print(isScaler_value2)

True


# Find the minimum product of two vector 

In [6]:
arr1 = [1,2,6,3,7]
arr2 = [10,7,45,3,7]
arr1.sort()
arr2.sort(reverse=True)
arr3 = 0
print(arr2)

[45, 10, 7, 7, 3]


In [7]:
for i in range(len(arr1)):
        arr3 += arr1[i]*arr2[i]
        

In [8]:
print(arr3)

149


## Write a program to work with vector

In [9]:
a = np.array([[1,2,3],[2,3,4],[2,4,6]])
b = np.array([[1,2,3],[2,3,4],[4,5,9]])
##3*3 matrix
c = a+b 
add = np.add(a,b)
print(add)

[[ 2  4  6]
 [ 4  6  8]
 [ 6  9 15]]


In [5]:
a = np.array([[1,2,3],[2,3,4]])
b = np.array([[1,2,3],[2,3,4]])
c = a*b
mul = np.multiply(a,b)
print(mul)

[[1 2 3]
 [2 3 4]]
[[ 1  4  9]
 [ 4  9 16]]


In [11]:
a = np.array([[1,2,3],[2,3,4]])
b = np.array([[1,2,3],[2,3,4]])
sub = np.subtract(a,b)
c = a-b
print(sub)

[[0 0 0]
 [0 0 0]]


In [12]:
a = "rs"
b = "am"

In [13]:
c = a[1]+b
d = a[0]+b
print(c,end = "\n")
print(d)

sam
ram


In [17]:
msg = "hello"
b = "j"
string_input = input("enter any char")
res = string_input + msg[1:]
res = b + msg[1:]
print(res)

enter any char
jello


In [18]:
msg = "hello"
b = "j"
# string_input = input("enter any char")
res = msg.replace(msg,b) + msg[1:]

print(res)

jello


In [ ]:
# a = [4,2,6]
# for i in range(len(a)):
#     for j in range(len(a-1)):
#         if(a[i]<a[j]):
#             a[i] = [j]

In [21]:
###################### 19/08/2022 ###############
A = np.mat("1 2; 3 4") ##2*2
print(A)

[[1 2]
 [3 4]]


In [23]:
print("Eigen Value", np.linalg.eigvals(A))
np.linalg.

Eigen Value [-0.37228132  5.37228132]


In [40]:
eigenvalue, eigenvector = np.linalg.eig(A)  ##eigenvalue & eigenvector

In [41]:
eigenvalue, eigenvector


(array([-0.37228132,  5.37228132]),
 matrix([[-0.82456484, -0.41597356],
         [ 0.56576746, -0.90937671]]))

In [42]:
B=[[12,3],[14,15]]  ##2*2 matrix

In [43]:
np.linalg.eigh(B)  ##eigen vector of B (for imaginary value)

(array([-0.58012784, 27.58012784]),
 array([[-0.7438189 ,  0.66838121],
        [ 0.66838121,  0.7438189 ]]))

# SINGULAR MATRIX (Matrix which diterminants = 0)

In [70]:
A=[[1,4],[1,4]]
B=[[6,3],[4,3]]
print(int(np.linalg.det(A))) ##check singular matrix
print(int(np.linalg.det(B))) ##check singular matrix
B

0
6


[[6, 3], [4, 3]]

In [71]:
print(np.linalg.inv(B)) ##find inverse of matrix

[[ 0.5        -0.5       ]
 [-0.66666667  1.        ]]


In [85]:
matrix1 = [[1,9,8], [2,7,6], [7,20,9]]
X = [4,2,-8]

In [86]:
E,V =  np.linalg.eig(matrix1)

In [87]:
E,V

(array([22.32558765, -0.87573002, -4.44985763]),
 array([[-0.46017333, -0.84332165, -0.62115879],
        [-0.37509519,  0.44438763, -0.27588126],
        [-0.80470125, -0.30220562,  0.73351979]]))

In [88]:
print(E[0],V[:,0]) ##for vector 1 only

22.3255876514531 [-0.46017333 -0.37509519 -0.80470125]


In [89]:
result = np.dot(matrix1,X)   ##for finding dot product
result

array([-42, -26,  -4])

In [94]:
eigenvalue = max((result))
print(eigenvalue)
eigenvalue = max(abs(result))
eigenvalue

-4


42

In [ ]:
##TASK 1

##write a program to find out the eigen value using power of iteration (using for iterate max 5 times)
## print thez output after diffrent diffrent itrations.

In [100]:
newmat = [[3,4],[7,4]]
print(int(np.linalg.det(newmat)))

-15
