In [9]:
import numpy as np

list1 = [1,2,3,4,5]

arr = np.asarray(list1)
print("list", arr)
print(type(arr))

list [1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
tuple1 = ([8, 4, 6])

tpl = np.asarray(tuple1)
print(type(tpl))
print(tuple1)
print()

<class 'numpy.ndarray'>
[8, 4, 6]



In [26]:
import numpy as np
a= np.array([[1,2],[5,6]])
b= np.array([[7,6],[5,9]])
print(np.add(a,b))


[[ 8  8]
 [10 15]]


In [12]:
print(np.subtract(a,b))

[[-6 -4  0]
 [ 2  0 -3]]


In [13]:
print(np.subtract(b,a))

[[ 6  4  0]
 [-2  0  3]]


In [16]:
print(np.divide(a,b))

[[0.14285714 0.33333333 1.        ]
 [2.         1.         0.66666667]]


In [17]:
print(np.divide(b,a))

[[7.  3.  1. ]
 [0.5 1.  1.5]]


In [19]:
print(np.multiply(a,b))

[[ 7 12 25]
 [ 8 25 54]]


In [38]:
print(np.multiply(b,a))

[[[ 7 12 12]
  [25 54  9]
  [25 36  9]]]


In [27]:
print(np.dot(b,a))

[[37 50]
 [50 64]]


In [43]:
import numpy as np
a= np.array([[[1,2,3],[5,6,3],[5,6,3]]])
b= np.array([[[7,6,4],[5,9,3],[5,6,3]]])
print(np.ndim(a))
print(np.shape(a))
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

print(np.dot(a,b))

3
(1, 3, 3)
[[[ 8  8  7]
  [10 15  6]
  [10 12  6]]]
[[[-6 -4 -1]
  [ 0 -3  0]
  [ 0  0  0]]]
[[[ 7 12 12]
  [25 54  9]
  [25 36  9]]]
[[[0.14285714 0.33333333 0.75      ]
  [1.         0.66666667 1.        ]
  [1.         1.         1.        ]]]
[[[[ 32  42  19]]

  [[ 80 102  47]]

  [[ 80 102  47]]]]


In [46]:
import numpy as np
a= np.array([[1,2],[5,6]])
b= np.array([5,6])
print(np.add(a,b))

# row broadcasting

[[ 6  8]
 [10 12]]


In [47]:
import numpy as np
a= np.array([[1,2],[5,6]])
b= np.array([5,6])
print(a.shape)
print(b.shape)
print(np.add(a,b))
# coloumn broadcasting

(2, 2)
(2,)
[[ 6  8]
 [10 12]]


In [48]:
# full broadcsting

import numpy as np
a= np.array([[1,2],[5,6]])
b= np.array([5])
print(a.shape)
print(b.shape)
print(np.add(a,b))

(2, 2)
(1,)
[[ 6  7]
 [10 11]]


In [51]:
import numpy as np
a= np.array([[[1,2,3],[5,6,3],[5,6,3]]])
b= np.array([[[7,6,4]]])
print(a.shape)
print(b.shape)
print(np.ndim(a))
print(np.add(a,b))


(1, 3, 3)
(1, 1, 3)
3
[[[ 8  8  7]
  [12 12  7]
  [12 12  7]]]


In [53]:
# full broadcasting
a= np.array([[[1,2,3],[5,6,3],[5,6,3]]])
b= np.array([[[7]]])
print(a.shape)
print(b.shape)
print(np.ndim(a))
print(np.add(a,b))

(1, 3, 3)
(1, 1, 1)
3
[[[ 8  9 10]
  [12 13 10]
  [12 13 10]]]


In [55]:
import pandas as pd 
import numpy as np

data = np.array(['a','b','c','d'])

series = pd.Series(data,index=[1,2,3,4])
print(series)

1    a
2    b
3    c
4    d
dtype: object


In [59]:
import pandas as pd 
import numpy as np


a= [['a',2],['b',6]]
print(a)
df=pd.DataFrame(a,columns=["name","age"],index=["row1","row2","row3"])
print(df)

[['a', 2], ['b', 6]]


ValueError: Shape of passed values is (2, 2), indices imply (3, 2)

In [64]:
import pandas as pd 
import numpy as np

data = np.array(['a','b','c','d'])

series = pd.Series(data,index=[1,2,3,4])
print(series)

df=series.to_frame()
print(df)

1    a
2    b
3    c
4    d
dtype: object
   0
1  a
2  b
3  c
4  d
